package notification

const (
	// Keystone
	projectCreated               = "identity.project.created"
	projectUpdated               = "identity.project.updated"
	projectDeleted               = "identity.project.deleted"
	projectRoleAssignmentCreated = "identity.role_assignment.created"
	projectRoleAssignmentDeleted = "identity.role_assignment.deleted"

	// Nova
	instanceCreated          = "compute.instance.create.end"
	instanceUpdated          = "compute.instance.update"
	instanceDeleted          = "compute.instance.delete.end"
	keypairCreated           = "keypair.create.end"
	keypairDeleted           = "keypair.delete.end"
	keypairImported          = "keypair.import.end"
	aggregateCreated         = "aggregate.create.end"
	aggregateDeleted         = "aggregate.delete.end"
	aggregatePropUpdated     = "aggregate.updateprop.end"
	aggregateMetadataUpdated = "aggregate.updatemetadata.end"
	aggregateHostAdded       = "aggregate.addhost.end"
	aggregateHostRemoved     = "aggregate.removehost.end"

	// Neutron
	networkCreated           = "network.create.end"
	networkUpdated           = "network.update.end"
	networkDeleted           = "network.delete.end"
	subnetCreated            = "subnet.create.end"
	subnetUpdated            = "subnet.update.end"
	subnetDeleted            = "subnet.delete.end"
	securityGroupCreated     = "security_group.create.end"
	securityGroupUpdated     = "security_group.update.end"
	securityGroupDeleted     = "security_group.delete.end"
	securityGroupRuleCreated = "security_group_rule.create.end"
	securityGroupRuleUpdated = "security_group_rule.update.end"
	securityGroupRuleDeleted = "security_group_rule.delete.end"
	routerCreated            = "router.create.end"
	routerUpdated            = "router.update.end"
	routerDeleted            = "router.delete.end"
	routerInterfaceCreated   = "router.interface.create"
	routerInterfaceDeleted   = "router.interface.delete"
	floatingIPCreated        = "floatingip.create.end"
	floatingIPUpdated        = "floatingip.update.end"
	floatingIPDeleted        = "floatingip.delete.end"
	portUpdated              = "port.update.end"
	portDeleted              = "port.delete.end"

	// Cinder
	volumeCreated               = "volume.create.end"
	volumeUpdated               = "volume.update.end"
	volumeDeleted               = "volume.delete.end"
	volumeAttached              = "volume.attach.end"
	volumeDetached              = "volume.detach.end"
	volumeManaged               = "volume.manage.end"
	volumeUnmanaged             = "volume.unmanage.end"
	volumeResized               = "volume.resize.end"
	volumeResetStatus           = "volume.reset_status.end"
	volumeRetyped               = "volume.retype"
	volumeSnapshotCreated       = "snapshot.create.end"
	volumeSnapshotUpdated       = "snapshot.update.end"
	volumeSnapshotDeleted       = "snapshot.delete.end"
	volumeSnapshotResetStatus   = "snapshot.reset_status.end"
	volumeTypeCreated           = "volume_type.create"
	volumeTypeUpdated           = "volume_type.update"
	volumeTypeDeleted           = "volume_type.delete"
	volumeTypeProjectAccessAdd  = "volume_type_project.access.add"
	volumeTypeExtraSpecsCreated = "volume_type_extra_specs.create"
	volumeTypeExtraSpecsDeleted = "volume_type_extra_specs.delete"
)
